# Generated by Django 4.1.5 on 2023-01-17 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_nombrehora_hora_nombrehora'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('idEstado', models.IntegerField(primary_key=True, serialize=False, verbose_name='id de Estado')),
                ('nombreEstado', models.CharField(max_length=70, verbose_name='Valor de la Estado')),
            ],
        ),
        migrations.AddField(
            model_name='reservacion',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.estado'),
        ),
    ]
