# Generated by Django 4.1.5 on 2023-01-17 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_estado_reservacion_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodega',
            name='idProducto',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='id de Producto'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='idCategoria',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='id de Categoria'),
        ),
        migrations.AlterField(
            model_name='estado',
            name='idEstado',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='id de Estado'),
        ),
        migrations.AlterField(
            model_name='fecha',
            name='idFecha',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='id de Fecha'),
        ),
        migrations.AlterField(
            model_name='hora',
            name='idHora',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='id de hora'),
        ),
        migrations.AlterField(
            model_name='plato',
            name='idPlato',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='id de Plato'),
        ),
        migrations.AlterField(
            model_name='reservacion',
            name='idReservacion',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='id de Reserva'),
        ),
    ]
