# Generated by Django 4.1.5 on 2023-01-22 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_reservacion_estado_pedido_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('idReceta', models.AutoField(primary_key=True, serialize=False, verbose_name='id de receta')),
                ('nombreReceta', models.CharField(max_length=70, verbose_name='Nombre de la receta')),
                ('descripcion', models.CharField(max_length=70, verbose_name='Descripcion de lareceta')),
            ],
        ),
    ]
