# Generated by Django 4.1.5 on 2023-01-22 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_receta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='descripcion',
            field=models.CharField(max_length=200, verbose_name='Descripcion de lareceta'),
        ),
    ]
