# Generated by Django 4.1.5 on 2023-01-22 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_receta_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nmesa',
            fields=[
                ('idNmesa', models.AutoField(primary_key=True, serialize=False, verbose_name='id de Estado')),
                ('nombreNmesa', models.CharField(max_length=70, verbose_name='Valor de la Estado')),
            ],
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='nombrePedido',
        ),
        migrations.AddField(
            model_name='pedido',
            name='numeroMesa',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Numero de mesa'),
        ),
    ]
