# Generated by Django 4.1.5 on 2023-01-22 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_nmesa_remove_pedido_nombrepedido_pedido_numeromesa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='descripcion',
            field=models.TextField(max_length=170, verbose_name='Descripcion de la receta'),
        ),
    ]
