# Generated by Django 3.1.2 on 2023-01-23 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_receta_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='nplato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.plato', verbose_name='Nombre del plato'),
        ),
        migrations.AlterField(
            model_name='receta',
            name='descripcion',
            field=models.TextField(max_length=250, verbose_name='Descripcion de la receta'),
        ),
    ]
