# Generated by Django 3.1.2 on 2023-01-23 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20230123_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disponible',
            fields=[
                ('idDisponible', models.AutoField(primary_key=True, serialize=False, verbose_name='id de Disponible')),
                ('nombreDisponible', models.CharField(max_length=70, verbose_name='Nombre de Disponible')),
            ],
        ),
        migrations.CreateModel(
            name='ProTipo',
            fields=[
                ('idTipo', models.AutoField(primary_key=True, serialize=False, verbose_name='id Tipo Producto')),
                ('nombreTipo', models.CharField(max_length=70, verbose_name='Nombre Tipo Producto')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('idProveedor', models.AutoField(primary_key=True, serialize=False, verbose_name='id de Proveedor')),
                ('nombreProveedor', models.CharField(max_length=70, verbose_name='Nombre de Proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False, verbose_name='Identificador')),
                ('nombreUsuario', models.CharField(max_length=70, verbose_name='Nombre')),
                ('aPaterno', models.CharField(max_length=70, verbose_name='Apellido Paterno')),
                ('aMaterno', models.CharField(max_length=70, verbose_name='Apellido Materno')),
                ('correo', models.CharField(max_length=50, verbose_name='Correo Electrónico')),
                ('pasw', models.CharField(max_length=20)),
                ('rol', models.CharField(max_length=20, verbose_name='Rol')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.AutoField(primary_key=True, serialize=False, verbose_name='id de Producto')),
                ('nombreProducto', models.CharField(max_length=70, verbose_name='Nombre de Producto')),
                ('cantidad', models.CharField(max_length=50, verbose_name='Cantidad')),
                ('proTipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.protipo')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('idMesa', models.AutoField(primary_key=True, serialize=False, verbose_name='id de Mesa')),
                ('numeroMesa', models.CharField(max_length=10, verbose_name='Numero de Mesa')),
                ('ubicacion', models.CharField(max_length=50, verbose_name='Ubicacion')),
                ('descripcion', models.CharField(max_length=70, verbose_name='Descripcion')),
                ('disponible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.disponible')),
            ],
        ),
    ]
