# Generated by Django 4.1.5 on 2023-01-25 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_disponible_mesa_producto_protipo_proveedor_usuario'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reservacion',
            unique_together={('fecha', 'hora')},
        ),
    ]
