# Generated by Django 4.1.5 on 2023-01-25 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_reservacion_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='numeroMesa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.mesa', verbose_name='Numero Mesa'),
        ),
    ]
