# Generated by Django 4.1.5 on 2023-01-26 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_pedido_numeromesa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='proTipo',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='proveedor',
        ),
    ]
