# Generated by Django 4.1.5 on 2023-01-26 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_producto_protipo_remove_producto_proveedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitar',
            fields=[
                ('idSolicitar', models.AutoField(primary_key=True, serialize=False, verbose_name='id de Producto')),
                ('nombreSolicitar', models.CharField(max_length=70, verbose_name='Nombre del Producto')),
                ('cantidadSolicitar', models.CharField(max_length=70, verbose_name='Cantidad de Producto')),
            ],
        ),
    ]
