# Generated by Django 4.1.5 on 2023-01-26 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_solicitar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('idBoleta', models.AutoField(primary_key=True, serialize=False, verbose_name='id de Boleta')),
                ('detalleBoleta', models.CharField(max_length=70, verbose_name='Detalle Boleta')),
                ('totalBoleta', models.IntegerField(verbose_name='Total Bolrta')),
            ],
        ),
    ]
