# Generated by Django 4.1.5 on 2023-01-26 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_boleta'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleta',
            name='numeroMesa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.mesa'),
        ),
    ]
