# Generated by Django 4.1.5 on 2023-01-26 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_boleta_numeromesa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleta',
            name='totalBoleta',
            field=models.IntegerField(verbose_name='Total Boleta'),
        ),
    ]
