# Generated by Django 3.1.2 on 2023-01-27 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_boleta_totalboleta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CantidadEmpleados', models.IntegerField(verbose_name='cantidad empleados')),
                ('CantidadReservas', models.IntegerField(verbose_name='cantidad reservas')),
                ('TotalVendido', models.IntegerField(verbose_name='total')),
                ('CantidadOrdenes', models.IntegerField(verbose_name='cantida de ordenes')),
                ('CantidadBoletas', models.IntegerField(verbose_name='cantidad de boletas')),
                ('TotalMesas', models.IntegerField(verbose_name='total de mesas')),
                ('Correo', models.CharField(max_length=70, verbose_name='correo')),
            ],
        ),
    ]
