# Generated by Django 3.1.2 on 2023-01-28 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_reporte'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('idRol', models.AutoField(primary_key=True, serialize=False, verbose_name='id rol')),
                ('nombreRol', models.CharField(max_length=30, verbose_name='Nombre Rol')),
            ],
        ),
        migrations.DeleteModel(
            name='ProTipo',
        ),
        migrations.DeleteModel(
            name='Proveedor',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.rol'),
        ),
    ]
